/**
 * CodeLens — OpenAPI 3.1 Specification Generator
 *
 * Transforms EndpointRecord[] into a complete OpenAPI 3.1 specification object,
 * then serializes it to YAML for consumption by Swagger UI, Postman, etc.
 *
 * Design decisions:
 *   - __UNRESOLVED__ schemas are emitted with a TODO description so the user
 *     knows what needs manual completion.
 *   - Unique type definitions from resolvedTypes are collected into
 *     components/schemas and referenced via $ref.
 *   - Uses js-yaml for YAML serialization (listed in package.json dependencies).
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import {
  EndpointRecord,
  JsonSchema,
  ParamRecord,
  ResponseSchemaRecord,
} from '../shared/types';
import { UNRESOLVED, HTTP_STATUS_DESCRIPTIONS } from '../shared/constants';
import { Logger } from '../shared/logger';

const logger = Logger.create('OpenAPIGenerator');

/** OpenAPI path item type — maps HTTP methods to operation objects */
type PathItem = Record<string, unknown>;

/** Collected component schemas keyed by type name */
type SchemaMap = Record<string, JsonSchema>;

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Generate a complete OpenAPI 3.1 specification object from endpoint records.
 *
 * @param endpoints - The enriched endpoint records (all tiers).
 * @returns A plain object representing a valid OpenAPI 3.1 document.
 */
export function generateOpenApiSpec(endpoints: EndpointRecord[]): object {
  const componentSchemas: SchemaMap = {};

  // Collect all unique resolved types into components/schemas
  for (const ep of endpoints) {
    if (ep.resolvedTypes) {
      for (const [typeName, schema] of Object.entries(ep.resolvedTypes)) {
        if (!componentSchemas[typeName]) {
          componentSchemas[typeName] = schema;
        }
      }
    }
  }

  // Group endpoints by path
  const pathMap = new Map<string, PathItem>();

  for (const ep of endpoints) {
    if (!pathMap.has(ep.path)) {
      pathMap.set(ep.path, {});
    }

    const pathItem = pathMap.get(ep.path)!;
    const method = ep.method.toLowerCase();

    pathItem[method] = buildOperation(ep, componentSchemas);
  }

  // Convert pathMap to plain object
  const paths: Record<string, PathItem> = {};
  for (const [pathKey, item] of pathMap) {
    paths[pathKey] = item;
  }

  // Build the top-level spec
  const spec: Record<string, unknown> = {
    openapi: '3.1.0',
    info: {
      title: 'API Documentation',
      description: 'Auto-generated by CodeLens. Review and update as needed.',
      version: '1.0.0',
    },
    paths,
  };

  // Add components/schemas if we have any
  if (Object.keys(componentSchemas).length > 0) {
    spec.components = {
      schemas: componentSchemas,
    };
  }

  // Add security schemes if any endpoints use auth
  const securitySchemes = collectSecuritySchemes(endpoints);
  if (Object.keys(securitySchemes).length > 0) {
    if (!spec.components) {
      spec.components = {};
    }
    (spec.components as Record<string, unknown>).securitySchemes = securitySchemes;
  }

  // Collect unique tags
  const tags = collectTags(endpoints);
  if (tags.length > 0) {
    spec.tags = tags.map((t) => ({ name: t }));
  }

  return spec;
}

/**
 * Write an OpenAPI specification object to a YAML file.
 *
 * @param spec       - The OpenAPI spec object (from generateOpenApiSpec).
 * @param outputPath - Absolute path to the output .yaml file.
 */
export async function writeOpenApiYaml(
  spec: object,
  outputPath: string,
): Promise<void> {
  const dir = path.dirname(outputPath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent = yaml.dump(spec, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
    quotingType: '"',
  });

  // Prepend a generated-file header
  const header = [
    '# ═══════════════════════════════════════════════════════════════════════════════',
    '# OpenAPI 3.1 Specification — Auto-generated by CodeLens',
    '# Generated at: ' + new Date().toISOString(),
    '#',
    '# WARNING: This file is auto-generated. Manual edits may be overwritten.',
    '# Fields marked TODO require manual review.',
    '# ═══════════════════════════════════════════════════════════════════════════════',
    '',
  ].join('\n');

  fs.writeFileSync(outputPath, header + yamlContent, 'utf-8');
  logger.info(`OpenAPI spec written to ${outputPath}`);
}

// ─── Internal Builders ───────────────────────────────────────────────────────

/**
 * Build an OpenAPI operation object for a single endpoint.
 */
function buildOperation(
  ep: EndpointRecord,
  componentSchemas: SchemaMap,
): Record<string, unknown> {
  const operation: Record<string, unknown> = {
    operationId: `${ep.handler.className ? ep.handler.className + '_' : ''}${ep.handler.name}`,
  };

  // Summary and description
  operation.summary = ep.summary ?? `${ep.method} ${ep.path}`;
  if (ep.description) {
    operation.description = ep.description;
  }

  // Tags
  if (ep.tags && ep.tags.length > 0) {
    operation.tags = ep.tags;
  }

  // Parameters (path, query, header, cookie — NOT body)
  const params = ep.params.filter((p) => p.in !== 'body');
  if (params.length > 0) {
    operation.parameters = params.map((p) => buildParameter(p));
  }

  // Request body
  if (ep.requestBody) {
    operation.requestBody = buildRequestBody(ep, componentSchemas);
  }

  // Responses
  operation.responses = buildResponses(ep);

  // Security
  if (ep.auth) {
    operation.security = [buildSecurityRequirement(ep.auth)];
  }

  // Extension: source location
  operation['x-source-file'] = ep.sourceFile;
  operation['x-source-lines'] = ep.sourceLines;
  operation['x-framework'] = ep.framework;

  return operation;
}

/**
 * Build an OpenAPI parameter object.
 */
function buildParameter(param: ParamRecord): Record<string, unknown> {
  const paramObj: Record<string, unknown> = {
    name: param.name,
    in: param.in,
    required: param.required,
  };

  if (param.description) {
    paramObj.description = param.description;
  }

  const schemaType = param.type === UNRESOLVED ? 'string' : param.type;
  paramObj.schema = { type: schemaType };

  if (param.type === UNRESOLVED) {
    paramObj.description = (paramObj.description ?? '') +
      ' (TODO: type could not be statically determined)';
  }

  if (param.default !== undefined) {
    (paramObj.schema as Record<string, unknown>).default = param.default;
  }

  return paramObj;
}

/**
 * Build an OpenAPI requestBody object.
 */
function buildRequestBody(
  ep: EndpointRecord,
  componentSchemas: SchemaMap,
): Record<string, unknown> {
  const rb = ep.requestBody!;

  let schema: JsonSchema | Record<string, unknown>;

  if (rb.schema === UNRESOLVED) {
    schema = {
      type: 'object',
      description: 'TODO: Request body schema could not be statically determined',
    };
  } else if (rb.typeName && componentSchemas[rb.typeName]) {
    // Reference the component schema
    schema = { $ref: `#/components/schemas/${rb.typeName}` };
  } else {
    schema = rb.schema;
  }

  return {
    required: rb.required,
    content: {
      [rb.contentType]: { schema },
    },
  };
}

/**
 * Build OpenAPI responses from Tier 2 response schemas or defaults.
 */
function buildResponses(ep: EndpointRecord): Record<string, unknown> {
  const responses: Record<string, unknown> = {};

  if (ep.responseSchemas && ep.responseSchemas.length > 0) {
    for (const rs of ep.responseSchemas) {
      const key = String(rs.statusCode);
      responses[key] = buildResponseObject(rs);
    }
  } else {
    // Default response when no Tier 2 data is available
    responses['200'] = {
      description: HTTP_STATUS_DESCRIPTIONS[200] || 'Successful response',
    };
  }

  return responses;
}

/**
 * Build a single OpenAPI response object.
 */
function buildResponseObject(rs: ResponseSchemaRecord): Record<string, unknown> {
  const desc =
    rs.description ??
    HTTP_STATUS_DESCRIPTIONS[rs.statusCode] ??
    `HTTP ${rs.statusCode}`;

  const responseObj: Record<string, unknown> = { description: desc };

  if (rs.schema !== UNRESOLVED) {
    responseObj.content = {
      [rs.contentType]: { schema: rs.schema },
    };
  } else {
    responseObj.content = {
      [rs.contentType]: {
        schema: {
          type: 'object',
          description: 'TODO: Response schema could not be statically determined',
        },
      },
    };
  }

  return responseObj;
}

/**
 * Collect unique security scheme definitions from endpoint auth records.
 */
function collectSecuritySchemes(
  endpoints: EndpointRecord[],
): Record<string, unknown> {
  const schemes: Record<string, unknown> = {};

  for (const ep of endpoints) {
    if (!ep.auth) continue;

    switch (ep.auth.type) {
      case 'bearer':
        schemes['bearerAuth'] = {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        };
        break;
      case 'api_key':
        schemes['apiKeyAuth'] = {
          type: 'apiKey',
          in: 'header',
          name: ep.auth.scheme ?? 'X-API-Key',
        };
        break;
      case 'basic':
        schemes['basicAuth'] = {
          type: 'http',
          scheme: 'basic',
        };
        break;
      case 'oauth2':
        schemes['oauth2'] = {
          type: 'oauth2',
          flows: {
            implicit: {
              authorizationUrl: 'https://example.com/oauth/authorize',
              scopes: {},
            },
          },
          description: 'TODO: Configure OAuth2 flows for your application',
        };
        break;
      case 'custom':
      case 'unknown':
        schemes['customAuth'] = {
          type: 'apiKey',
          in: 'header',
          name: 'Authorization',
          description: `TODO: Custom auth scheme detected (${ep.auth.scheme ?? 'unknown'}). Configure manually.`,
        };
        break;
    }
  }

  return schemes;
}

/**
 * Build a security requirement object for an endpoint.
 */
function buildSecurityRequirement(
  auth: NonNullable<EndpointRecord['auth']>,
): Record<string, string[]> {
  switch (auth.type) {
    case 'bearer':
      return { bearerAuth: [] };
    case 'api_key':
      return { apiKeyAuth: [] };
    case 'basic':
      return { basicAuth: [] };
    case 'oauth2':
      return { oauth2: [] };
    default:
      return { customAuth: [] };
  }
}

/**
 * Collect unique tags from all endpoints.
 */
function collectTags(endpoints: EndpointRecord[]): string[] {
  const tagSet = new Set<string>();
  for (const ep of endpoints) {
    if (ep.tags) {
      for (const tag of ep.tags) {
        tagSet.add(tag);
      }
    }
  }
  return Array.from(tagSet).sort();
}
